package com.melodix.player.core.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential

/**
 * Obtains a Google ID token via Credential Manager for Firebase Auth. [serverClientId] is
 * R.string.default_web_client_id, generated by the google-services plugin from google-services.json.
 * Must be called with an Activity context so the account bottom sheet can display.
 */
class GoogleAuthClient(private val serverClientId: String) {

    suspend fun getGoogleIdToken(activityContext: Context): Result<String> = runCatching {
        val option = GetGoogleIdOption.Builder()
            .setServerClientId(serverClientId)
            .setFilterByAuthorizedAccounts(false) // first sign-in: offer all accounts
            .setAutoSelectEnabled(true)           // auto-pick on return visits
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(option)
            .build()

        val response = CredentialManager.create(activityContext)
            .getCredential(activityContext, request)

        GoogleIdTokenCredential.createFrom(response.credential.data).idToken
    }
}
